apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 554382655594.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 554382655594.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: ac2be793
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
